
        //Get part
        const Remainder_Form_Base10_Get_Arrays=[
            //Number Base is : 10
            // Remainder : 0
            [
                [0,1,2,3,4,5,6,7,8,9,10],
                [0,null,null,null,null,null,null,null,null,null,1],
                [0,5,null,null,null,null,null,null,null,null,2],
                [0,null,null,null,null,null,null,null,null,null,1],
                [0,5,null,null,null,null,null,null,null,null,2],
                [0,2,4,6,8,null,null,null,null,null,5],
                [0,5,null,null,null,null,null,null,null,null,2],
                [0,null,null,null,null,null,null,null,null,null,1],
                [0,5,null,null,null,null,null,null,null,null,2],
                [0,null,null,null,null,null,null,null,null,null,1]
            ],
            // Remainder : 1
            [
                [null,null,null,null,null,null,null,null,null,null,0],
                [1,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,0],
                [7,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,0],
                [null,null,null,null,null,null,null,null,null,null,0],
                [null,null,null,null,null,null,null,null,null,null,0],
                [3,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,0],
                [9,null,null,null,null,null,null,null,null,null,1]
            ],
            // Remainder : 2
            [
                [null,null,null,null,null,null,null,null,null,null,0],
                [2,null,null,null,null,null,null,null,null,null,1],
                [1,6,null,null,null,null,null,null,null,null,2],
                [4,null,null,null,null,null,null,null,null,null,1],
                [3,8,null,null,null,null,null,null,null,null,2],
                [null,null,null,null,null,null,null,null,null,null,0],
                [2,7,null,null,null,null,null,null,null,null,2],
                [6,null,null,null,null,null,null,null,null,null,1],
                [4,9,null,null,null,null,null,null,null,null,2],
                [8,null,null,null,null,null,null,null,null,null,1]
            ],
            // Remainder : 3
            [
                [null,null,null,null,null,null,null,null,null,null,0],
                [3,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,0],
                [1,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,0],
                [null,null,null,null,null,null,null,null,null,null,0],
                [null,null,null,null,null,null,null,null,null,null,0],
                [9,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,0],
                [7,null,null,null,null,null,null,null,null,null,1]
            ],
            // Remainder : 4
            [
                [null,null,null,null,null,null,null,null,null,null,0],
                [4,null,null,null,null,null,null,null,null,null,1],
                [2,7,null,null,null,null,null,null,null,null,2],
                [8,null,null,null,null,null,null,null,null,null,1],
                [1,6,null,null,null,null,null,null,null,null,2],
                [null,null,null,null,null,null,null,null,null,null,0],
                [4,9,null,null,null,null,null,null,null,null,2],
                [2,null,null,null,null,null,null,null,null,null,1],
                [3,8,null,null,null,null,null,null,null,null,2],
                [6,null,null,null,null,null,null,null,null,null,1]
            ],
            // Remainder : 5
            [
                [null,null,null,null,null,null,null,null,null,null,0],
                [5,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,0],

                [5,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,0],
                [1,3,5,7,9,null,null,null,null,null,5],
                [null,null,null,null,null,null,null,null,null,null,0],
                [5,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,0],
                [5,null,null,null,null,null,null,null,null,null,1]
            ],
            // Remainder : 6
            [
                [null,null,null,null,null,null,null,null,null,null,0],
                [6,null,null,null,null,null,null,null,null,null,1],
                [3,8,null,null,null,null,null,null,null,null,2],
                [2,null,null,null,null,null,null,null,null,null,1],
                [4,9,null,null,null,null,null,null,null,null,2],
                [null,null,null,null,null,null,null,null,null,null,0],
                [1,6,null,null,null,null,null,null,null,null,2],
                [8,null,null,null,null,null,null,null,null,null,1],
                [2,7,null,null,null,null,null,null,null,null,2],
                [4,null,null,null,null,null,null,null,null,null,1]
            ],
            // Remainder : 7
            [
                [null,null,null,null,null,null,null,null,null,null,0],
                [7,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,0],
                [9,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,0],
                [null,null,null,null,null,null,null,null,null,null,0],
                [null,null,null,null,null,null,null,null,null,null,0],
                [1,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,0],
                [3,null,null,null,null,null,null,null,null,null,1]
            ],
            // Remainder : 8
            [
                [null,null,null,null,null,null,null,null,null,null,0],
                [8,null,null,null,null,null,null,null,null,null,1],
                [4,9,null,null,null,null,null,null,null,null,2],
                [6,null,null,null,null,null,null,null,null,null,1],
                [2,7,null,null,null,null,null,null,null,null,2],
                [null,null,null,null,null,null,null,null,null,null,0],
                [3,8,null,null,null,null,null,null,null,null,2],
                [4,null,null,null,null,null,null,null,null,null,1],
                [1,6,null,null,null,null,null,null,null,null,2],
                [2,null,null,null,null,null,null,null,null,null,1]
            ],
            // Remainder : 9
            [
                [null,null,null,null,null,null,null,null,null,null,0],
                [9,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,0],
                [3,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,0],
                [null,null,null,null,null,null,null,null,null,null,0],
                [null,null,null,null,null,null,null,null,null,null,0],
                [7,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,0],
                [1,null,null,null,null,null,null,null,null,null,1]
            ]
        ];
        const Remainder_Form_Base16_Get_Arrays=[
            //Number Base is : 16
            // Remainder : 0
            [
                [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16],
                [0,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [0,8,null,null,null,null,null,null,null,null,null,null,null,null,null,null,2],
                [0,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [0,4,8,12,null,null,null,null,null,null,null,null,null,null,null,null,4],
                [0,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [0,8,null,null,null,null,null,null,null,null,null,null,null,null,null,null,2],
                [0,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [0,2,4,6,8,10,12,14,null,null,null,null,null,null,null,null,8],
                [0,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [0,8,null,null,null,null,null,null,null,null,null,null,null,null,null,null,2],
                [0,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [0,4,8,12,null,null,null,null,null,null,null,null,null,null,null,null,4],
                [0,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [0,8,null,null,null,null,null,null,null,null,null,null,null,null,null,null,2],
                [0,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1]
            ],
            // Remainder : 1
            [
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [11,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [13,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [7,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [9,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [3,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [5,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [15,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1]
            ],
            // Remainder : 2
            [
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [2,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [1,9,null,null,null,null,null,null,null,null,null,null,null,null,null,null,2],
                [6,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [10,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [3,11,null,null,null,null,null,null,null,null,null,null,null,null,null,null,2],
                [14,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [2,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [5,13,null,null,null,null,null,null,null,null,null,null,null,null,null,null,2],
                [6,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [10,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [7,15,null,null,null,null,null,null,null,null,null,null,null,null,null,null,2],
                [14,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1]
            ],
            // Remainder : 3
            [
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [3,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [7,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [5,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [11,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [9,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [15,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [13,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1]
            ],
            // Remainder : 4
            [
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [4,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [2,10,null,null,null,null,null,null,null,null,null,null,null,null,null,null,2],
                [12,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [1,5,9,13,null,null,null,null,null,null,null,null,null,null,null,null,4],
                [4,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [6,14,null,null,null,null,null,null,null,null,null,null,null,null,null,null,2],
                [12,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [4,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [2,10,null,null,null,null,null,null,null,null,null,null,null,null,null,null,2],
                [12,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [3,7,11,15,null,null,null,null,null,null,null,null,null,null,null,null,4],
                [4,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [6,14,null,null,null,null,null,null,null,null,null,null,null,null,null,null,2],
                [12,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1]
            ],
            // Remainder : 5
            [
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [5,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [7,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [3,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [13,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [15,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [9,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [11,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1]
            ],
            // Remainder : 6
            [
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [6,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [3,11,null,null,null,null,null,null,null,null,null,null,null,null,null,null,2],
                [2,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [14,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [1,9,null,null,null,null,null,null,null,null,null,null,null,null,null,null,2],
                [10,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [6,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [7,15,null,null,null,null,null,null,null,null,null,null,null,null,null,null,2],
                [2,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [14,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [5,13,null,null,null,null,null,null,null,null,null,null,null,null,null,null,2],
                [10,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1]
            ],
            // Remainder : 7
            [
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [7,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [13,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [11,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [15,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [5,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [3,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [9,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1]
            ],
            // Remainder : 8
            [
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [8,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [4,12,null,null,null,null,null,null,null,null,null,null,null,null,null,null,2],
                [8,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [2,6,10,14,null,null,null,null,null,null,null,null,null,null,null,null,4],
                [8,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [4,12,null,null,null,null,null,null,null,null,null,null,null,null,null,null,2],
                [8,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [1,3,5,7,9,11,13,15,null,null,null,null,null,null,null,null,8],
                [8,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [4,12,null,null,null,null,null,null,null,null,null,null,null,null,null,null,2],
                [8,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [2,6,10,14,null,null,null,null,null,null,null,null,null,null,null,null,4],
                [8,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [4,12,null,null,null,null,null,null,null,null,null,null,null,null,null,null,2],
                [8,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1]
            ],
            // Remainder : 9
            [
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [9,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [3,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [5,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [15,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [11,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [13,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [7,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1]
            ],
            // Remainder : 10
            [
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [10,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [5,13,null,null,null,null,null,null,null,null,null,null,null,null,null,null,2],
                [14,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [2,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [7,15,null,null,null,null,null,null,null,null,null,null,null,null,null,null,2],
                [6,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [10,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [1,9,null,null,null,null,null,null,null,null,null,null,null,null,null,null,2],
                [14,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [2,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [3,11,null,null,null,null,null,null,null,null,null,null,null,null,null,null,2],
                [6,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1]
            ],
            // Remainder : 11
            [
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [11,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [9,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [15,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [13,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [3,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [7,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [5,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1]
            ],
            // Remainder : 12
            [
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [12,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [6,14,null,null,null,null,null,null,null,null,null,null,null,null,null,null,2],
                [4,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [3,7,11,15,null,null,null,null,null,null,null,null,null,null,null,null,4],
                [12,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [2,10,null,null,null,null,null,null,null,null,null,null,null,null,null,null,2],
                [4,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [12,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [6,14,null,null,null,null,null,null,null,null,null,null,null,null,null,null,2],
                [4,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [1,5,9,13,null,null,null,null,null,null,null,null,null,null,null,null,4],
                [12,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [2,10,null,null,null,null,null,null,null,null,null,null,null,null,null,null,2],
                [4,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1]
            ],
            // Remainder : 13
            [
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [13,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [15,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [9,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [11,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [5,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [7,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [3,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1]
            ],
            // Remainder : 14
            [
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [14,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [7,15,null,null,null,null,null,null,null,null,null,null,null,null,null,null,2],
                [10,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [6,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [5,13,null,null,null,null,null,null,null,null,null,null,null,null,null,null,2],
                [2,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [14,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [3,11,null,null,null,null,null,null,null,null,null,null,null,null,null,null,2],
                [10,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [6,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [1,9,null,null,null,null,null,null,null,null,null,null,null,null,null,null,2],
                [2,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1]
            ],
            // Remainder : 15
            [
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [15,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [5,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [3,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [9,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [7,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [13,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [11,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1],
                [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0],
                [1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1]
            ]
        ];